### ISSUE TITLE
Сделать фигуру водосборника

### ISSUE THREAD

**Issue by Obsidian-pb** [Obsidian-pb/GraFiS-Tactic#1]
Необходимо сделать фигуру водосборника которая работала бы как разветвление, но ровно наоборот - собирала поток от нескольких рукавных линий в один.

**Comment by AlxVasilchenko** [comment]
Нужно внедрить процедуру обновления данных соединений, когда ВС подключен в НРС и изменяется его свойство пользователем (сборник/разветвитель)
